<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <AssemblyTitle>Windows Service Wrapper</AssemblyTitle>
    <Description>Allows arbitrary process to run as a Windows service by wrapping it.</Description>
    <Company>CloudBees, Inc.</Company>
    <Product>Windows Service Wrapper</Product>
    <Copyright>Copyright (c) 2008-2020 Kohsuke Kawaguchi, Sun Microsystems, Inc., CloudBees, Inc., Oleg Nenashev and other contributors</Copyright>
  </PropertyGroup>

  <PropertyGroup>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>partial</TrimMode>
    <DebuggerSupport>false</DebuggerSupport>
    <NullabilityInfoContextSupport>false</NullabilityInfoContextSupport>
    <_AggressiveAttributeTrimming>true</_AggressiveAttributeTrimming>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net7.0-windows' AND '$(RuntimeIdentifier)' != ''">
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' != 'net7.0-windows'">
    <ILMergeVersion>3.0.41</ILMergeVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' != 'net7.0-windows'">
    <PackageReference Include="ilmerge" Version="$(ILMergeVersion)" />
    <Reference Include="System.ServiceProcess" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WinSW.Core\WinSW.Core.csproj" />
    <ProjectReference Include="..\WinSW.Plugins\WinSW.Plugins.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' != 'net7.0-windows'">
    <ProjectReference Include="..\WinSW.Tasks\WinSW.Tasks.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <Target Name="PublishCoreExe" AfterTargets="Publish" Condition="'$(TargetFramework)' == 'net7.0-windows'">

    <MakeDir Directories="$(ArtifactsPublishDir)" />
    <Copy SourceFiles="$(PublishDir)$(TargetName).exe" DestinationFiles="$(ArtifactsPublishDir)WinSW-$(PlatformTarget).exe" />

  </Target>



</Project>
